export const testimonials = [
  {
    id: 1,
    name: "Compass31041884377",
    rating: 5,
    text: "While waiting for my flight, I was relaxing at the lobby of Grand Mercure Hotel and noticed the Sastikaa Travel desk. Since I had some free time, I decided to try their Batu Caves Half Day Tour. It turned out to be a wonderful decision! The Batu Caves visit was amazing and the playful monkeys around the temple made the experience even more fun and memorable.",
    image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/32/ac/68/a4/caption.jpg?w=800&h=-1&s=1",
    avatar: "https://i.pravatar.cc/150?u=Compass31041884377",
  },
  {
    id: 2,
    name: "Wander33428579703",
    rating: 5,
    text: "Fantastic Genting tour with driver Kalai! He was very professional and patient, making the whole trip enjoyable and stress-free. Everything from pickup to drop-off was perfectly organized. Highly recommended!",
    image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/32/a4/ec/17/caption.jpg?w=600&h=-1&s=1",
    avatar: "https://i.pravatar.cc/150?u=Wander33428579703",
  },
  {
    id: 3,
    name: "Escape32555618590",
    rating: 5,
    text: "Excellent airport transfer service! The driver was punctual, professional, and the vehicle was very clean and comfortable. Highly recommended service.",
    image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/32/a0/bd/80/caption.jpg?w=800&h=-1&s=1",
    avatar: "https://i.pravatar.cc/150?u=Escape32555618590",
  },
  {
    id: 4,
    name: "Markus",
    rating: 5,
    text: "The tour was very enjoyable and well organized. Our driver, Kalai, was friendly and welcoming. She drove us to the different sights, explained each stop beforehand, and then gave us time to explore on our own. Overall, it was a great experience, and we highly recommend the tour.",
    image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/32/8b/3b/3a/caption.jpg?w=1400&h=-1&s=1",
    avatar: "https://i.pravatar.cc/150?u=Markus",
  },
  {
    id: 5,
    name: "Umar M",
    rating: 5,
    text: "We had a wonderful time with Alen. Batu Caves was awesome! We will definitely come back to Kuala Lumpur to explore different states and enjoy new experiences.",
    image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/32/a0/c3/77/caption.jpg?w=800&h=-1&s=1",
    avatar: "https://i.pravatar.cc/150?u=UmarM",
  },
  {
    id: 6,
    name: "Olawale Ajibowo",
    rating: 5,
    text: "Had an amazing experience and my tour guide Kalai is a wonderful lady. The stairs and monkeys at Batu Caves makes it memorable.",
    image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/31/9e/2f/c4/caption.jpg?w=200&h=200&s=1x",
    avatar: "https://i.pravatar.cc/150?u=OlawaleAjibowo",
  },
];
