export const ENDPOINTS = {
  server: {
    session: '/v1/b2c-admin/auth/session',
    b2bMe: '/b2b/admin/me',
    bookingsAll: '/v1/b2c/bookings/all',
    destinations: '/v1/b2c/destinations',
    reviews: '/v1/b2c/reviews',
    packageById: (id: string) => `/v1/b2c-admin/packages/${id}`,
    packages: '/v1/b2c-admin/packages?isAdmin=true&limit=100&excludeActivities=true',
    activities: '/v1/b2c-admin/packages?isAdmin=true&limit=100&onlyActivities=true',
  },
  client: {
    websiteHero: {
      active: (t: number) => `/website-hero/active?t=${t}`,
      list: '/admin/website-hero',
      byId: (id: string) => `/admin/website-hero/${id}`,
    },
    reviews: {
      adminList: '/reviews/admin',
      create: '/reviews',
      byId: (id: string) => `/reviews/${id}`,
      move: (id: string) => `/reviews/${id}/move`,
      normalize: '/reviews/normalize',
    },
    upload: {
      image: '/upload/image',
      all: (params?: { folder?: string; limit?: number; nextCursor?: string }) => {
        const q = params ? '?' + new URLSearchParams(params as any).toString() : '';
        return `/upload/all${q}`;
      },
    },
    stories: {
      list: '/admin/stories',
      byId: (id: string) => `/admin/stories/${id}`,
      move: (id: string) => `/admin/stories/${id}/move`,
      normalize: '/admin/stories/normalize',
      public: '/stories',
    },
    destinations: {
      list: '/destinations',
      byId: (id: string) => `/destinations/${id}`,
      move: (id: string) => `/destinations/${id}/move`,
      normalize: '/destinations/normalize',
    },
    analytics: {
      daily: '/analytics/daily',
      dailyDetail: (date: string) => `/analytics/daily/${date}`,
      overview: '/analytics/overview',
      distribution: '/analytics/distribution',
      visitors: '/analytics/visitors',
      visitorProfile: (visitorId: string, date?: string) =>
        `/analytics/visitors/${encodeURIComponent(visitorId)}${date ? `?date=${date}` : ''}`,
    },
    bookings: {
      // Rewrites via apiClient to v1/b2c/bookings/all (b2c gateway)
      admin: 'bookings/all',
    },
    metrics: {
      dashboard: 'admin/metrics',
      queueHealth: 'admin/queue/health',
    },
    blogs: {
      list: '/blogs',
      adminList: 'admin/blogs',
      adminById: (id: string) => `admin/blogs/${id}`,
      byId: (id: string) => `/blogs/${id}`,
      bySlug: (slug: string) => `/blogs/${slug}`,
      like: (id: string) => `/blogs/${id}/like`,
      legacyAdminById: (id: string) => `/blogs/admin/${id}`,
    },
    uiConfig: {
      hero: 'ui-config/website-hero',
      adminHero: 'admin/ui-config/website-hero',
    },
    b2b: {
      login: 'b2b/admin/login',
      forgotPassword: 'b2b/admin/forgot-password',
      resetPassword: 'b2b/admin/reset-password',
      logout: 'b2b/admin/logout',
      refresh: 'b2b/admin/refresh',
      agencies: 'b2b/admin/agencies',
      agencyById: (id: string) => `b2b/admin/agencies/${id}`,
      agencyAction: (id: string, action: 'approve' | 'reject' | 'suspend' | 'reactivate') => `b2b/admin/agencies/${id}/${action}`,
      agencyStatusLog: (id: string) => `b2b/admin/agencies/${id}/status-log`,
      // Quote admin endpoints
      quotes: 'b2b/admin/quotes',
      quoteById: (id: string) => `b2b/admin/quotes/${id}`,
      quoteStatusUpdate: (id: string) => `b2b/admin/quotes/${id}/status`,
      quotesByAgency: (agencyId: string) => `b2b/admin/agencies/${agencyId}/quotes`,
      cities: 'b2b/admin/cities',
      cityById: (id: string) => `b2b/admin/cities/${id}`,
      hotels: 'b2b/admin/hotels',
      hotelById: (id: string) => `b2b/admin/hotels/${id}`,
      packages: 'b2b/admin/packages',
      packageById: (id: string) => `b2b/admin/packages/${id}`,
      proposals: 'b2b/admin/proposals',
      proposalStatusUpdate: (id: string) => `b2b/admin/proposals/${id}/status`,
    },
    auth: {
      login: 'admin/login',
      register: 'admin/register',
      forgotPassword: 'admin/forgot-password',
      resetPassword: 'admin/reset-password',
      logout: 'admin/logout',
      session: 'admin/session',
      createPackage: 'admin/packages/create',
      updatePackage: (id: string) => `admin/packages/updatePackage/${id}`,
      packageById: (id: string) => `admin/packages/${id}`,
      deletePackage: (id: string) => `admin/packages/deletePackage/${id}`,
      updateRank: (id: string) => `admin/packages/updateRank/${id}`,
      toggleStatus: (id: string) => `admin/packages/toggleStatus/${id}`,
      takenRanks: 'admin/packages/takenRanks',
      // Must be b2c path — admin/bookings/all would rewrite to missing v1/b2c-admin/bookings/all
      bookingsAll: 'bookings/all',
    },
    devops: {
      bootstrap: 'v1/devops/auth/bootstrap',
      otpVerify: 'v1/devops/auth/otp/verify',
      totpSetup: 'v1/devops/auth/totp/setup',
      totpVerify: 'v1/devops/auth/totp/verify',
      deviceRegister: 'v1/devops/auth/device/register',
      deviceVerify: 'v1/devops/auth/device/verify',
      sessionIssue: 'v1/devops/auth/session',
      session: 'v1/devops/auth/session',
      logout: 'v1/devops/auth/logout',
      executive: 'v1/devops/executive/summary',
      healthApps: 'v1/devops/health/apps',
      healthInfra: 'v1/devops/health/infra',
      apiRequests: 'v1/devops/api/requests',
      apiPerformance: 'v1/devops/api/performance',
      apiObservability: 'v1/devops/api/observability',
      apiRollup: 'v1/devops/api/observability/rollup',
      errors: 'v1/devops/errors',
      errorById: (fp: string) => `v1/devops/errors/${encodeURIComponent(fp)}`,
      logsSearch: 'v1/devops/logs/search',
      retention: 'v1/devops/meta/retention',
      capacityOverview: 'v1/devops/capacity/overview',
      capacityMongodb: 'v1/devops/capacity/mongodb',
      capacityCollections: 'v1/devops/capacity/collections',
      capacityDisk: 'v1/devops/capacity/disk',
      capacityMemory: 'v1/devops/capacity/memory',
      capacityForecast: 'v1/devops/capacity/forecast',
      capacityAlerts: 'v1/devops/capacity/alerts',
      capacityApps: 'v1/devops/capacity/apps',
      capacityCloud: 'v1/devops/capacity/cloud',
      businessSummary: 'v1/devops/business/summary',
      trafficSummary: 'v1/devops/traffic/summary',
      securitySummary: 'v1/devops/security/summary',
      queuesSummary: 'v1/devops/queues/summary',
      deploySummary: 'v1/devops/deploy/summary',
      auditLogs: 'v1/devops/audit/logs',
      alerts: 'v1/devops/alerts',
      alertById: (fp: string) =>
        `v1/devops/alerts/${encodeURIComponent(fp)}`,
    },
  },
} as const;
